version: "3.9"
services:
    api:
        build:
            context: .
            # use Dockerfile.gpu when using a NVIDIA GPU
            dockerfile: Dockerfile.gpu
        ports:
            - "3000:3000"
        volumes:
            - .:/workspace
            - /home/vision/.cache:/root/.cache
        depends_on:
            - redis
        environment:
            - BASE_URL
            - EMAIL_SENDER_ADDRESS
            - EMAIL_SENDER_PASSWORD
            - EMAIL_SENDER_HOST
            - DISCLAIMER
            - ALLOWED_WEBHOOKS_FILE
        command: gunicorn -w 2 -b 0.0.0.0:3000 --log-file=- 'src.main:app'
        restart: always
    worker:
        build:
            context: .
            # use Dockerfile.gpu when using a NVIDIA GPU
            dockerfile: Dockerfile.gpu
        volumes:
            - .:/workspace
            - /home/vision/.cache:/root/.cache
        depends_on:
            - redis
        environment:
            - BASE_URL
            - EMAIL_SENDER_ADDRESS
            - EMAIL_SENDER_PASSWORD
            - EMAIL_SENDER_HOST
            - ALLOWED_WEBHOOKS_FILE
        command: rq worker --url redis://redis:6379 -c worker-settings
        # Uncomment the following lines when using a NVIDIA GPU
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
        restart: always

    redis:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        restart: always

volumes:
    redis-data:
